---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Add users to the docker group.
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_group_members }}"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- include_tasks: docker-compose.yml
  when: docker_install_compose
